VERSION 0.8

FROM golang:1.21-alpine3.19

deps:
    WORKDIR /work

    RUN apk add --no-cache gcc musl-dev
    DO ../earthly/go+DEPS
    RUN type ginkgo # ginkgo Exists
    
test:
    FROM +deps
    RUN type ginkgo